# Generated by Django 4.2.9 on 2024-02-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Готово', 'Готово'), ('Не готово', 'Не готово')], default='Не готово', max_length=9),
        ),
    ]
